title: Gajan Kanagenthiran
description: Project Portfoilo 
[Link To GitHub Repository of “Centre-Forward” Project](https://github.com/GK2103/Centre-Forward-Market-Value-Analysis) 
[Link To GitHub Repository of WeightLess App](https://github.com/GK2103/WeightLess)
[Link To GitHub Repository of COVID-19 Dashboard](https://github.com/GK2103/COVID-19DashBoard) 

theme: jekyll-theme-minimal
